export const USER_LIST_FOR_CURRENT_ACCOUNT_SUCCESS = 'USER_LIST_FOR_CURRENT_ACCOUNT_SUCCESS';
export const UPDATE_PAGE_TITLE = 'UPDATE_PAGE_TITLE';

export const SAVE_USER_SETTINGS_SUCCESS = 'SAVE_USER_SETTINGS_SUCCESS';
export const SAVE_USER_SETTINGS_FAILURE = 'SAVE_USER_SETTINGS_FAILURE';
export const GET_USER_SETTINGS_SUCCESS = 'GET_USER_SETTINGS_SUCCESS';
export const GET_USER_SETTINGS_FAILURE = 'GET_USER_SETTINGS_FAILURE';

export const HIDE_ALERT_MESSAGE = 'HIDE_ALERT_MESSAGE';
export const SHOW_ALERT_MESSAGE = 'SHOW_ALERT_MESSAGE';

export const LOGIN_USER = 'LOGIN USER';
export const LOAD_CURRENT_USER = 'LOAD_CURRENT_USER';
export const LOGOUT = 'LOGOUT';

export const INIT_REQUEST = 'INIT_REQUEST';
export const INIT_SUCCESS = 'INIT_SUCCESS';
export const INIT_FAILURE = 'INIT_FAILURE';

// Get current user(me) from token in localStorage
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const LOAD_USER_FAILURE = 'LOAD_USER_FAILURE';
export const RESET_TOKEN = 'RESET_TOKEN';
export const USERS_HIDE_FLASH_MESSAGE = 'USERS_HIDE_FLASH_MESSAGE';

export const CLIENT_MODE_REQUEST = 'CLIENT_MODE_REQUEST';
export const CLIENT_MODE_SUCCESS = 'CLIENT_MODE_SUCCESS';

// Project
export const PROJECTS_FETCH = 'PROJECTS_FETCH';
export const PROJECT_NOTES_CHANGE_FILTER = 'PROJECT_NOTES_CHANGE_FILTER';
export const PROJECT_LIST_REQUEST = 'PROJECT_LIST_REQUEST';
export const PROJECT_LIST_SUCCESS = 'PROJECT_LIST_SUCCESS';
export const PROJECT_LIST_FAILURE = 'PROJECT_LIST_FAILURE';
export const PROJECT_FEATURES_SUCCESS = 'PROJECT_FEATURES_SUCCESS';
export const PROJECT_FEATURES_FAILURE = 'PROJECT_FEATURES_FAILURE';
export const PROJECTS_CHANGE_QUERY = 'PROJECTS_CHANGE_QUERY';
export const PROJECTS_CHANGE_FILTER = 'PROJECTS_CHANGE_FILTER';

export const PROJECT_EXTRA_INFO_SUCCESS = 'PROJECT_EXTRA_INFO_SUCCESS';
export const PROJECT_EXTRA_INFO_FAILURE = 'PROJECT_EXTRA_INFO_FAILURE';

export const PROJECT_DETAIL_REQUEST = 'PROJECT_DETAIL_REQUEST';
export const PROJECT_DETAIL_SUCCESS = 'PROJECT_DETAIL_SUCCESS';
export const PROJECT_DETAIL_FAILURE = 'PROJECT_DETAIL_FAILURE';
export const UPDATE_PROJECT_DETAIL = 'UPDATE_PROJECT_DETAIL';
export const UPDATE_PROJECT_DETAIL_SUCCESS = 'UPDATE_PROJECT_DETAIL_SUCCESS';
export const UPDATE_PROJECT_DETAIL_FAILURE = 'UPDATE_PROJECT_DETAIL_FAILURE';

export const PROJECT_POSITION_SUCCESS = 'PROJECT_POSITION_SUCCESS';
export const SAVE_PROJECT_POSITION = 'SAVE_PROJECT_POSITION';
export const SAVE_PROJECT_POSITION_SUCCESS = 'SAVE_PROJECT_POSITION_SUCCESS';
export const SAVE_PROJECT_POSITION_FAILURE = 'SAVE_PROJECT_POSITION_FAILURE';
export const PROJECTS_CHANGE_PAGE_NUMBER = 'PROJECTS_CHANGE_PAGE_NUMBER';
export const PROJECTS_CHANGE_SORT_BY = 'PROJECTS_CHANGE_SORT_BY';

export const PROJECT_CANDIDACIES_REQUEST = 'PROJECT_CANDIDACIES_REQUEST';
export const PROJECT_CANDIDACIES_SUCCESS = 'PROJECT_CANDIDACIES_SUCCESS';
export const PROJECT_CANDIDACY_SUCCESS = 'PROJECT_CANDIDACY_SUCCESS';
export const PROJECT_CANDIDACY_FAILURE = 'PROJECT_CANDIDACY_FAILURE';
export const PROJECT_CANDIDACIES_FAILURE = 'PROJECT_CANDIDACIES_FAILURE';
export const CANDIDACIES_CHANGE_PAGE_NUMBER = 'CANDIDACIES_CHANGE_PAGE_NUMBER';
export const CANDIDACIES_CHANGE_SORT_BY = 'CANDIDACIES_CHANGE_SORT_BY';
export const CANDIDACIES_CHANGE_FILTER = 'CANDIDACIES_CHANGE_FILTER';
export const CANDIDACIES_CHANGE_FILTER_ONLY = 'CANDIDACIES_CHANGE_FILTER_ONLY';

export const PROJECT_NEW_REQUEST = 'PROJECT_NEW_REQUEST';
export const PROJECT_ADD_REQUEST_SUCCESS = 'PROJECT_ADD_REQUEST_SUCCESS';
export const PROJECT_ADD_REQUEST_FAILURE = 'PROJECT_ADD_REQUEST_FAILURE';
export const PROJECT_CLIENT_LIST_SUCCESS = 'PROJECT_CLIENT_LIST_SUCCESS';
export const PROJECT_CLIENT_LIST_FAILURE = 'PROJECT_CLIENT_LIST_FAILURE';
export const ADD_MEMBERS_TO_PROJECTS_SUCCESS = 'ADD_MEMBERS_TO_PROJECTS_SUCCESS';
export const ADD_MEMBERS_TO_PROJECTS_FAILURE = 'ADD_MEMBERS_TO_PROJECTS_FAILURE';
export const PROJECT_DISPLAY_SUCCESS = 'PROJECT_DISPLAY_SUCCESS';
export const ADD_PROJECT_CLIENT_SUCCESS = 'ADD_PROJECT_CLIENT_SUCCESS';
export const CANDIDACIES_BULK_UPDATE_SUCCESS = 'CANDIDACIES_BULK_UPDATE_SUCCESS';
export const CANDIDACIES_BULK_TASK_LIST_SUCCESS = 'CANDIDACIES_BULK_TASK_LIST_SUCCESS';
export const CANDIDACIES_BULK_ADD_PROJECT_SUCCESS = 'CANDIDACIES_BULK_ADD_PROJECT_SUCCESS';
export const PROJECTS_EXPORT_SUCCESS = 'PROJECTS_EXPORT_SUCCESS';
export const CANDIDATES_EXPORT_SUCCESS = 'CANDIDATES_EXPORT_SUCCESS';
export const CANDIDATES_BULK_NOTE_ADD_SUCCESS = 'CANDIDATES_BULK_NOTE_ADD_SUCCESS';
export const PROJECT_MEATADATA_SUCCESS = 'PROJECT_MEATADATA_SUCCESS';
export const PROJECT_FEE_SUCCESS = 'PROJECT_FEE_SUCCESS';
export const REMOVE_PROJECT_SPECIALTY_SUCCESS = 'REMOVE_PROJECT_SPECIALTY_SUCCESS';
export const REMOVE_PROJECT_INDUSTRY_SUCCESS = 'REMOVE_PROJECT_INDUSTRY_SUCCESS';
export const REMOVE_PROJECT_INVESTOR_SUCCESS = 'REMOVE_PROJECT_INVESTOR_SUCCESS';
export const UPDATE_PROJECT_FEE_SUCCESS = 'UPDATE_PROJECT_FEE_SUCCESS';
export const UPDATE_PROJECT_FEE_FAILURE = 'UPDATE_PROJECT_FEE_FAILURE';
export const PROJECT_MEATADATA_FAILURE = 'PROJECT_MEATADATA_FAILURE';
export const PROJECT_FEE_FAILURE = 'PROJECT_FEE_FAILURE';
export const PROJECT_NOTES_REQUEST = 'PROJECT_NOTES_REQUEST';
export const PROJECT_NOTES_SUCCESS = 'PROJECT_NOTES_SUCCESS';
export const PROJECT_NOTES_FAILURE = 'PROJECT_NOTES_FAILURE';
export const ADD_NOTE_TO_PROJECT_SUCCESS = 'ADD_NOTE_TO_PROJECT_SUCCESS';
export const ADD_NOTE_TO_PROJECT_FAILURE = 'ADD_NOTE_TO_PROJECT_FAILURE';
export const UPDATE_NOTE_TO_PROJECT_SUCCESS = 'UPDATE_NOTE_TO_PROJECT_SUCCESS';
export const UPDATE_NOTE_TO_PROJECT_FAILURE = 'UPDATE_NOTE_TO_PROJECT_FAILURE';
export const REPLY_TO_PROJECT_NOTE_SUCCESS = 'REPLY_TO_PROJECT_NOTE_SUCCESS';
export const REPLY_TO_PROJECT_NOTE_FAILURE = 'REPLY_TO_PROJECT_NOTE_FAILURE';
export const FETCH_PROJECT_NOTE_SUCCESS = 'FETCH_PROJECT_NOTE_SUCCESS';
export const FETCH_PROJECT_NOTE_FAILURE = 'FETCH_PROJECT_NOTE_FAILURE';
export const DELETE_PROJECT_NOTE_SUCCESS = 'DELETE_PROJECT_NOTE_SUCCESS';
export const DELETE_PROJECT_NOTE_FAILURE = 'DELETE_PROJECT_NOTE_FAILURE';
export const FETCH_PROJECT_PINNED_NOTE_SUCCESS = 'FETCH_PROJECT_PINNED_NOTE_SUCCESS';
export const PIN_PROJECT_NOTE_SUCCESS = 'PIN_PROJECT_NOTE_SUCCESS';
export const UNPIN_PROJECT_NOTE_SUCCESS = 'UNPIN_PROJECT_NOTE_SUCCESS';
export const CANDIDACY_RANK_UPDATE_SUCCESS = 'CANDIDACY_RANK_UPDATE_SUCCESS';
export const SAVE_PROJECT_STRATEGY = 'SAVE_PROJECT_STRATEGY';
export const ADD_CANDIDACIES_FAILURE = 'ADD_CANDIDACIES_FAILURE';
export const ADD_CANDIDACIES_SUCCESS = 'ADD_CANDIDACIES_SUCCESS';
export const CANDIDACY_OVERVIEW_SUCCESS = 'CANDIDACY_OVERVIEW_SUCCESS';
export const CANDIDACY_OVERVIEW_FAILURE = 'CANDIDACY_OVERVIEW_FAILURE';
export const REORDER_CANDIDACIES_BY_DND = 'REORDER_CANDIDACIES_BY_DND';
export const UPDATE_PROJECT_FIELDS_LIST = 'UPDATE_PROJECT_FIELDS_LIST';
export const PROJECTS_AUTOCOMPLETE_SUCCESS = 'PROJECTS_AUTOCOMPLETE_SUCCESS';
export const PROJECT_PAYMENTS_SUCCESS = 'PROJECT_PAYMENTS_SUCCESS';
export const ADD_PROJECT_PAYMENT_SUCCESS = 'ADD_PROJECT_PAYMENT_SUCCESS';
export const ADD_PROJECT_PAYMENT_FAILURE = 'ADD_PROJECT_PAYMENT_FAILURE';
export const UPDATE_PROJECT_PAYMENT_SUCCESS = 'UPDATE_PROJECT_PAYMENT_SUCCESS';
export const UPDATE_PROJECT_PAYMENT_FAILURE = 'UPDATE_PROJECT_PAYMENT_FAILURE';
export const DELETE_PROJECT_PAYMENT_SUCCESS = 'DELETE_PROJECT_PAYMENT_SUCCESS';
export const DELETE_PROJECT_PAYMENT_FAILURE = 'DELETE_PROJECT_PAYMENT_FAILURE';
export const PROJECT_ATTACHMENTS_SUCCESS = 'PROJECT_ATTACHMENTS_SUCCESS';
export const ADD_PROJECT_ATTACHMENT_SUCCESS = 'ADD_PROJECT_ATTACHMENT_SUCCESS';
export const ADD_PROJECT_ATTACHMENT_FAILURE = 'ADD_PROJECT_ATTACHMENT_FAILURE';
export const BULK_ADD_PROJECT_ATTACHMENT_SUCCESS = 'BULK_ADD_PROJECT_ATTACHMENT_SUCCESS';
export const BULK_ADD_PROJECT_ATTACHMENT_FAILURE = 'BULK_ADD_PROJECT_ATTACHMENT_FAILURE';
export const UPDATE_PROJECT_ATTACHMENT_SUCCESS = 'UPDATE_PROJECT_ATTACHMENT_SUCCESS';
export const UPDATE_PROJECT_ATTACHMENT_FAILURE = 'UPDATE_PROJECT_ATTACHMENT_FAILURE';
export const DELETE_PROJECT_ATTACHMENT_SUCCESS = 'DELETE_PROJECT_ATTACHMENT_SUCCESS';
export const DELETE_PROJECT_ATTACHMENT_FAILURE = 'DELETE_PROJECT_ATTACHMENT_FAILURE';
export const BULK_DELETE_PROJECT_ATTACHMENT_SUCCESS = 'BULK_DELETE_PROJECT_ATTACHMENT_SUCCESS';
export const BULK_DELETE_PROJECT_ATTACHMENT_FAILURE = 'BULK_DELETE_PROJECT_ATTACHMENT_FAILURE';
export const IMPORT_PEOPLE_TO_PROJECT_SUCCESS = 'IMPORT_PEOPLE_TO_PROJECT_SUCCESS';
export const IMPORT_PEOPLE_TO_PROJECT_FAILURE = 'IMPORT_PEOPLE_TO_PROJECT_FAILURE';
export const PROJECT_EXPORT_SUCCESS = 'PROJECT_EXPORT_SUCCESS';
export const PROJECT_EXPORT_FAILURE = 'PROJECT_EXPORT_FAILURE';
export const PROJECT_CHANGE_FILTER_SETTING = 'PROJECT_CHANGE_FILTER_SETTING';
export const PROJECT_PROFILE_SUCCESS = 'PROJECT_PROFILE_SUCCESS';
export const REQUEST_PROJECT_IDS_SUCCESS = 'REQUEST_PROJECT_IDS_SUCCESS';
export const REQUEST_PROJECT_IDS_FAILURE = 'REQUEST_PROJECT_IDS_FAILURE';

// Project Categories
export const FETCH_PROJECT_CATEGORIES_SUCCESS = 'FETCH_PROJECT_CATEGORIES_SUCCESS';
export const FETCH_PROJECT_CATEGORIES_FAILURE = 'FETCH_PROJECT_CATEGORIES_FAILURE';
export const CREATE_PROJECT_CATEGORY_SUCCESS = 'CREATE_PROJECT_CATEGORY_SUCCESS';
export const CREATE_PROJECT_CATEGORY_FAILURE = 'CREATE_PROJECT_CATEGORY_FAILURE';
export const UPDATE_PROJECT_CATEGORY_SUCCESS = 'UPDATE_PROJECT_CATEGORY_SUCCESS,';
export const UPDATE_PROJECT_CATEGORY_FAILURE = '  UPDATE_PROJECT_CATEGORY_FAILURE,';
export const DELETE_PROJECT_CATEGORY_SUCCESS = 'DELETE_PROJECT_CATEGORY_SUCCESS';
export const DELETE_PROJECT_CATEGORY_FAILURE = 'DELETE_PROJECT_CATEGORY_FAILURE';

// Project Location
export const REQUEST_PROJECT_LOCATION_SUCCESS = 'REQUEST_PROJECT_LOCATION_SUCCESS';
export const REQUEST_PROJECT_LOCATION_FAILURE = 'REQUEST_PROJECT_LOCATION_FAILURE';
export const UPDATE_PROJECT_LOCATION_SUCCESS = 'UPDATE_PROJECT_LOCATION_SUCCESS';
export const UPDATE_PROJECT_LOCATION_FAILURE = 'UPDATE_PROJECT_LOCATION_FAILURE';

// Project Viewed At
export const PROJECT_UPDATE_VIEWED_AT_SUCCESS = 'PROJECT_UPDATE_VIEWED_AT_SUCCESS';
export const PROJECT_UPDATE_VIEWED_AT_FAILURE = 'PROJECT_UPDATE_VIEWED_AT_FAILURE';

// Source Companies
export const UPDATE_SOURCE_COMPANY_SUCCESS = 'UPDATE_SOURCE_COMPANY_SUCCESS';
export const UPDATE_SOURCE_COMPANY_FAILURE = 'UPDATE_SOURCE_COMPANY_FAILURE';
export const FETCH_SOURCE_COMPANY_STATS_SUCCESS = 'FETCH_SOURCE_COMPANY_STATS_SUCCESS';
export const FETCH_SOURCE_COMPANY_STATS_FAILURE = 'FETCH_SOURCE_COMPANY_STATS_FAILURE';

// PEOPLE
export const UPDATE_PERSON = 'UPDATE_PERSON';
export const UPDATE_PERSON_SUCCESS = 'UPDATE_PERSON_SUCCESS';
export const UPDATE_PERSON_FAILURE = 'UPDATE_PERSON_FAILURE';
export const PERSON_ADD_REQUEST_SUCCESS = 'PERSON_ADD_REQUEST_SUCCESS';
export const PERSON_ADD_REQUEST_FAILURE = 'PERSON_ADD_REQUEST_FAILURE';
export const PEOPLE_FETCH_SUCCESS = 'PEOPLE_FETCH_SUCCESS';
export const PEOPLE_FETCH_FAILURE = 'PEOPLE_FETCH_FAILURE';
export const PEOPLE_LIST_REQUEST = 'PEOPLE_LIST_REQUEST';
export const PEOPLE_LIST_FETCH_SUCCESS = 'PEOPLE_LIST_FETCH_SUCCESS';
export const PEOPLE_LIST_FETCH_FAILURE = 'PEOPLE_LIST_FETCH_FAILURE';
export const PEOPLE_LIST_BY_IDS_FETCH_SUCCESS = 'PEOPLE_LIST_BY_IDS_FETCH_SUCCESS';
export const PEOPLE_LIST_BY_IDS_FETCH_FAILURE = 'PEOPLE_LIST_BY_IDS_FETCH_FAILURE';
export const PERSON_RELATIONSHIP_ADD_SUCCESS = 'PERSON_RELATIONSHIP_ADD_SUCCESS';
export const PERSON_RELATIONSHIP_ADD_FAILURE = 'PERSON_RELATIONSHIP_ADD_FAILURE';
export const PEOPLE_CHANGE_PAGE_NUMBER = 'PEOPLE_CHANGE_PAGE_NUMBER';
export const PEOPLE_CHANGE_PER_PAGE = 'PEOPLE_CHANGE_PER_PAGE';
export const PEOPLE_CHANGE_SORT_BY = 'PEOPLE_CHANGE_SORT_BY';
export const PEOPLE_HIDE_FLASH_MESSAGE = 'PEOPLE_HIDE_FLASH_MESSAGE';
export const PEOPLE_CHANGE_QUERY = 'PEOPLE_CHANGE_QUERY';
export const PEOPLE_CHANGE_FILTER_SETTING = 'PEOPLE_CHANGE_FILTER_SETTING';
export const REQUEST_PEOPLE_IDS_SUCCESS = 'REQUEST_PEOPLE_IDS_SUCCESS';
export const REQUEST_PEOPLE_IDS_FAILURE = 'REQUEST_PEOPLE_IDS_FAILURE';


export const PERSON_CONTACT_INFO_SUCCESS = 'PERSON_CONTACT_INFO_SUCCESS';
export const PERSON_CONTACT_INFO_FAILURE = 'PERSON_CONTACT_INFO_FAILURE';
export const CREATE_NOTES_SUCCESS = 'CREATE_NOTES_SUCCESS';
export const CREATE_NOTES_FAILURE = 'CREATE_NOTES_FAILURE';
export const UPDATE_NOTE_SUCCESS = 'UPDATE_NOTE_SUCCESS';
export const UPDATE_NOTE_FAILURE = 'UPDATE_NOTE_FAILURE';

export const PERSON_POSITIONS_FAILURE = 'PERSON_POSITIONS_FAILURE';
export const PERSON_POSITIONS_SUCCESS = 'PERSON_POSITIONS_SUCCESS';
export const CREATE_PERSON_POSITION_SUCCESS = 'CREATE_PERSON_POSITION_SUCCESS';
export const CREATE_PERSON_POSITION_FAILURE = 'CREATE_PERSON_POSITION_FAILURE';
export const CREATE_PERSON_POSITION = 'CREATE_PERSON_POSITION';
export const UPDATE_PERSON_POSITION_SUCCESS = 'UPDATE_PERSON_POSITION_SUCCESS';
export const UPDATE_PERSON_POSITION_FAILURE = 'UPDATE_PERSON_POSITION_FAILURE';
export const UPDATE_PERSON_POSITION = 'UPDATE_PERSON_POSITION';
export const DELETE_PERSON_POSITION_SUCCESS = 'DELETE_PERSON_POSITION_SUCCESS';
export const DELETE_PERSON_POSITION_FAILURE = 'DELETE_PERSON_POSITION_FAILURE';
export const DELETE_PERSON_POSITION = 'DELETE_PERSON_POSITION';

export const PERSON_EDUCATIONS_FAILURE = 'PERSON_EDUCATIONS_FAILURE';
export const PERSON_EDUCATIONS_SUCCESS = 'PERSON_EDUCATIONS_SUCCESS';

export const UPDATE_PERSON_EDUCATION_SUCCESS = 'UPDATE_PERSON_EDUCATION_SUCCESS';
export const UPDATE_PERSON_EDUCATION_FAILURE = 'UPDATE_PERSON_EDUCATION_FAILURE';
export const UPDATE_PERSON_EDUCATION = 'UPDATE_PERSON_EDUCATION';
export const CREATE_PERSON_EDUCATION_SUCCESS = 'CREATE_PERSON_EDUCATION_SUCCESS';
export const CREATE_PERSON_EDUCATION_FAILURE = 'CREATE_PERSON_EDUCATION_FAILURE';
export const DELETE_PERSON_EDUCATION_SUCCESS = 'DELETE_PERSON_EDUCATION_SUCCESS';
export const DELETE_PERSON_EDUCATION_FAILURE = 'DELETE_PERSON_EDUCATION_FAILURE';
export const DELETE_PERSON_EDUCATION = 'DELETE_PERSON_EDUCATION';

export const CREATE_PERSON_EMAIL_SUCCESS = 'CREATE_PERSON_EMAIL_SUCCESS';
export const CREATE_PERSON_EMAIL_FAILURE = 'CREATE_PERSON_EMAIL_FAILURE';
export const UPDATE_PERSON_EMAIL_SUCCESS = 'UPDATE_PERSON_EMAIL_SUCCESS';
export const UPDATE_PERSON_EMAIL_FAILURE = 'UPDATE_PERSON_EMAIL_FAILURE';
export const DELETE_PERSON_EMAIL_SUCCESS = 'DELETE_PERSON_EMAIL_SUCCESS';
export const DELETE_PERSON_EMAIL_FAILURE = 'DELETE_PERSON_EMAIL_FAILURE';

export const CREATE_PERSON_PHONE_NUMBER_SUCCESS = 'CREATE_PERSON_PHONE_NUMBER_SUCCESS';
export const CREATE_PERSON_PHONE_NUMBER_FAILURE = 'CREATE_PERSON_PHONE_NUMBER_FAILURE';
export const UPDATE_PERSON_PHONE_NUMBER_SUCCESS = 'UPDATE_PERSON_PHONE_NUMBER_SUCCESS';
export const UPDATE_PERSON_PHONE_NUMBER_FAILURE = 'UPDATE_PERSON_PHONE_NUMBER_FAILURE';
export const DELETE_PERSON_PHONE_NUMBER_SUCCESS = 'DELETE_PERSON_PHONE_NUMBER_SUCCESS';
export const DELETE_PERSON_PHONE_NUMBER_FAILURE = 'DELETE_PERSON_PHONE_NUMBER_FAILURE';
export const DELETE_PERSON_PHONE_NUMBER = 'DELETE_PERSON_PHONE_NUMBER';

export const CREATE_PERSON_COMPENSATION_SUCCESS = 'CREATE_PERSON_COMPENSATION_SUCCESS';
export const CREATE_PERSON_COMPENSATION_FAILURE = 'CREATE_PERSON_COMPENSATION_FAILURE';
export const UPDATE_PERSON_COMPENSATION_SUCCESS = 'UPDATE_PERSON_COMPENSATION_SUCCESS';
export const UPDATE_PERSON_COMPENSATION_FAILURE = 'UPDATE_PERSON_COMPENSATION_FAILURE';
export const DELETE_PERSON_COMPENSATION_SUCCESS = 'DELETE_PERSON_COMPENSATION_SUCCESS';
export const DELETE_PERSON_COMPENSATION_FAILURE = 'DELETE_PERSON_COMPENSATION_FAILURE';

export const PERSON_PROJECTS_SUCCESS = 'PERSON_PROJECTS_SUCCESS';
export const PERSON_PROJECTS_FAILURE = 'PERSON_PROJECTS_FAILURE';

export const PERSON_DETAIL_REQUEST = 'PERSON_DETAIL_REQUEST';
export const PERSON_DETAIL_SUCCESS = 'PERSON_DETAIL_SUCCESS';
export const PERSON_DETAIL_FAILURE = 'PERSON_DETAIL_FAILURE';

export const PERSON_RELATIONSHIP_TYPE_SUCCESS = 'PERSON_RELATIONSHIP_TYPE_SUCCESS';
export const PEOPLE_CHANGE_FILTER = 'PEOPLE_CHANGE_FILTER';
export const UPDATE_PERSON_OVERVIEW = 'UPDATE_PERSON_OVERVIEW';
export const UPDATE_PERSON_OVERVIEW_SUCCESS = 'UPDATE_PERSON_OVERVIEW_SUCCESS';
export const UPDATE_PERSON_OVERVIEW_FAILURE = 'UPDATE_PERSON_OVERVIEW_FAILURE';
export const PERSON_RELATIONSHIP_DELETE_SUCCESS = 'PERSON_RELATIONSHIP_DELETE_SUCCESS';
export const PERSON_RELATIONSHIP_DELETE_FAILURE = 'PERSON_RELATIONSHIP_DELETE_FAILURE';
export const ADD_TO_PROJECT_SUCCESS = 'ADD_TO_PROJECT_SUCCESS';
export const ADD_TO_PROJECT_FAILURE = 'ADD_TO_PROJECT_FAILURE';
export const ADD_NOTE_SUCCESS = 'ADD_NOTE_SUCCESS';
export const ADD_NOTE_FAILURE = 'ADD_NOTE_FAILURE';
export const MERGE_PEOPLE_SUCCESS = 'MERGE_PEOPLE_SUCCESS';
export const MERGE_PEOPLE_FAILURE = 'MERGE_PEOPLE_FAILURE';
export const ADD_TAGS_SUCCESS = 'ADD_TAGS_SUCCESS';
export const ADD_TAGS_FAILURE = 'ADD_TAGS_FAILURE';
export const PEOPLE_EXPORT_SUCCESS = 'PEOPLE_EXPORT_SUCCESS';
export const ADD_NOTE_TO_PERSON_SUCCESS = 'ADD_NOTE_TO_PERSON_SUCCESS';
export const ADD_NOTE_TO_PERSON_FAILURE = 'ADD_NOTE_TO_PERSON_FAILURE';
export const PERSON_ATTACH_FILE_FROM_EMAIL = 'PERSON_ATTACH_FILE_FROM_EMAIL';
export const PERSON_COMPENSATION_SUCCESS = 'PERSON_COMPENSATION_SUCCESS';
export const IMPORT_PERSON_CONTACT_SUCCESS = 'IMPORT_PERSON_CONTACT_SUCCESS';
export const IMPORT_PERSON_CONTACT_FAILURE = 'IMPORT_PERSON_CONTACT_FAILURE';
export const PERSON_CANDIDACIES_UPDATE_SUCCESS = 'PERSON_CANDIDACIES_UPDATE_SUCCESS';
export const PERSON_CANDIDACIES_UPDATE_FAILURE = 'PERSON_CANDIDACIES_UPDATE_FAILURE';
export const PEOPLE_TAGS_SUCCESS = 'PEOPLE_TAGS_SUCCESS';
export const PEOPLE_TAGS_FAILURE = 'PEOPLE_TAGS_FAILURE';
export const UPDATE_PERSON_FIELDS_LIST = 'UPDATE_PERSON_FIELDS_LIST';
export const UPDATE_PERSON_COLUMN_WIDTHS = 'UPDATE_PERSON_COLUMN_WIDTHS';
export const PERSON_CLIENT_PROJECTS_SUCCESS = 'PERSON_CLIENT_PROJECTS_SUCCESS';
export const PERSON_CLIENT_PROJECTS_FAILURE = 'PERSON_CLIENT_PROJECTS_FAILURE';
export const REQUEST_EMAILS_LIST = 'REQUEST_EMAILS_LIST';
export const PERSON_EMAILS_SUCCESS = 'PERSON_EMAILS_SUCCESS';
export const PERSON_EMAILS_FAILURE = 'PERSON_EMAILS_FAILURE';
export const PERSON_EMAILS_CHANGE_SORT_BY = 'PERSON_EMAILS_CHANGE_SORT_BY';
export const PEOPLE_QUICK_SEARCH_SUCCESS = 'PEOPLE_QUICK_SEARCH_SUCCESS';
export const PEOPLE_EXTRA_INFO_SUCCESS = 'PEOPLE_EXTRA_INFO_SUCCESS';
export const PEOPLE_EXTRA_INFO_FAILURE = 'PEOPLE_EXTRA_INFO_FAILURE';

export const FETCH_CANDIDACY_PANEL_TAB_VIEWS = 'FETCH_CANDIDACY_PANEL_TAB_VIEWS';
export const UPDATE_CANDIDACY_PANEL_TAB_VIEWS = 'UPDATE_CANDIDACY_PANEL_TAB_VIEWS';
export const UPDATE_PERSON_SIDE_PANEL_CURRENT_TAB_LIST = 'UPDATE_PERSON_SIDE_PANEL_CURRENT_TAB_LIST';

export const PERSON_BULK_EDIT_REQUEST_SUCCESS = 'PERSON_BULK_EDIT_REQUEST_SUCCESS';

// Deals
export const DEAL_LIST_REQUEST = 'DEAL_LIST_REQUEST';
export const DEAL_LIST_SUCCESS = 'DEAL_LIST_SUCCESS';
export const DEAL_LIST_FAILURE = 'DEAL_LIST_FAILURE';
export const REQUEST_DEAL_LEADS_SUCCESS = 'REQUEST_DEAL_LEADS_SUCCESS';
export const DEAL_CHANGE_PAGE_NUMBER = 'DEAL_CHANGE_PAGE_NUMBER';
export const DEAL_CHANGE_SORT_BY = 'DEAL_CHANGE_SORT_BY';
export const DEAL_CHANGE_FILTER = 'DEAL_CHANGE_FILTER';
export const DEAL_CHANGE_QUERY = 'DEAL_CHANGE_QUERY';

export const DEALS_EXPORT_SUCCESS = 'DEALS_EXPORT_SUCCESS';

export const UPDATE_DEALS_FIELDS_LIST = 'UPDATE_DEALS_FIELDS_LIST';
export const UPDATE_DEAL_COLUMN_WIDTHS = 'UPDATE_DEAL_COLUMN_WIDTHS';
export const DEAL_EXTRA_INFO_SUCCESS = 'DEAL_EXTRA_INFO_SUCCESS';
export const DEAL_EXTRA_INFO_FAILURE = 'DEAL_EXTRA_INFO_FAILURE';

export const ADD_NOTE_TO_DEAL_TARGET_SUCCESS = 'ADD_NOTE_TO_DEAL_TARGET_SUCCESS';
export const ADD_NOTE_TO_DEAL_TARGET_FAILURE = 'ADD_NOTE_TO_DEAL_TARGET_FAILURE';
export const DEAL_CHANGE_FILTER_SETTING = 'DEAL_CHANGE_FILTER_SETTING';

export const CREATE_DEAL_SUCCESS = 'CREATE_DEAL_SUCCESS';
export const UPDATE_DEAL_SUCCESS = 'UPDATE_DEAL_SUCCESS';
export const UPDATE_DEAL_FAILURE = 'UPDATE_DEAL_FAILURE';

export const DEAL_CUSTOM_FIELDS_INFO_SUCCESS = 'DEAL_CUSTOM_FIELDS_INFO_SUCCESS';
export const DEAL_CUSTOM_FIELDS_INFO_FAILURE = 'DEAL_CUSTOM_FIELDS_INFO_FAILURE';

// Static Data
export const FUNDING_STAGES_SUCCESS = 'FUNDING_STAGES_SUCCESS';
export const REVENUE_RANGES_SUCCESS = 'REVENUE_RANGES_SUCCESS';
export const EMPLOYEE_RANGES_SUCCESS = 'EMPLOYEE_RANGES_SUCCESS';
export const REGIONS_SUCCESS = 'REGIONS_SUCCESS';
export const GLOBAL_REGIONS_SUCCESS = 'GLOBAL_REGIONS_SUCCESS';
export const CURRENCIES_SUCCESS = 'CURRENCIES_SUCCESS';
export const FIRM_STATUSES_SUCCESS = 'FIRM_STATUSES_SUCCESS';
export const LOCATION_TYPES_SUCCESS = 'LOCATION_TYPES_SUCCESS';
export const INSTANT_MESSAGE_ACCOUNT_TYPES_SUCCESS = 'INSTANT_MESSAGE_ACCOUNT_TYPES_SUCCESS';
export const COUNTRY_SUCCESS = 'COUNTRY_SUCCESS';
export const TASK_CATEGORY_LIST_SUCCESS = 'TASK_CATEGORY_LIST_SUCCESS';
export const NOTE_CATEGORY_SUCCESS = 'NOTE_CATEGORY_SUCCESS';
export const TIMEZONES_SUCCESS = 'TIMEZONES_SUCCESS';
export const REQUEST_PROJECT_STATUS_LIST_SUCCESS = 'REQUEST_PROJECT_STATUS_LIST_SUCCESS';
export const REQUEST_DEAL_STATUSES_SUCCESS = 'REQUEST_DEAL_STATUSES_SUCCESS';

// tags
export const TAGS_CHANGE_PAGE_NUMBER = 'TAGS_CHANGE_PAGE_NUMBER';
export const REQUEST_TAG_LIST = 'REQUEST_TAG_LIST';
export const TAG_LIST_SUCCESS = 'TAG_LIST_SUCCESS';
export const CREATE_TAG_SUCCESS = 'CREATE_TAG_SUCCESS';
export const CREATE_TAG_FAILURE = 'CREATE_TAG_FAILURE';
export const REQUEST_MANAGE_TAG = 'REQUEST_MANAGE_TAG';
export const UPDATE_TAG_SUCCESS = 'UPDATE_TAG_SUCCESS';
export const UPDATE_TAG_FAILURE = 'UPDATE_TAG_FAILURE';
export const DELETE_TAG_SUCCESS = 'DELETE_TAG_SUCCESS';
export const DELETE_TAG_FAILURE = 'DELETE_TAG_FAILURE';
export const TAG_SORT_BY_NAME = 'TAG_SORT_BY_NAME';
export const TAG_LIST_FILTER = 'TAG_LIST_FILTER';
export const TAG_HIDE_FLASH_MESSAGE = 'TAG_HIDE_FLASH_MESSAGE';

export const TAG_STATS_LIST_SUCCESS = 'TAG_STATS_LIST_SUCCESS';
export const REQUEST_TAG_STATS_LIST = 'REQUEST_TAG_STATS_LIST';

export const TAG_AUTOCOMPLETE_SUCCESS = 'TAG_AUTOCOMPLETE_SUCCESS';

export const FETCH_TAGS_RELATED_COMPANIES_SUCCESS = 'FETCH_TAGS_RELATED_COMPANIES_SUCCESS';
export const FETCH_TAGS_RELATED_COMPANIES_FAILURE = 'FETCH_TAGS_RELATED_COMPANIES_FAILURE';
export const ADD_TAG_IN_BULK_SUCCESS = 'ADD_TAG_IN_BULK_SUCCESS';
export const ADD_TAG_IN_BULK_FAILURE = 'ADD_TAG_IN_BULK_FAILURE';

// tasks
export const TASK_LIST_SUCCESS = 'TASK_LIST_SUCCESS';
export const TASK_ASSIGNEES_LIST_SUCCESS = 'TASK_ASSIGNEES_LIST_SUCCESS';
export const TASK_ADD_REQUEST_SUCCESS = 'TASK_ADD_REQUEST_SUCCESS';
export const TASK_ADD_REQUEST_FAILURE = 'TASK_ADD_REQUEST_FAILURE';
export const TASK_LIST_REQUEST = 'TASK_LIST_REQUEST';
export const TASKS_COUNT_SUCCESS = ' TASKS_COUNT_SUCCESS';

// dashboard
export const DASHBOARD_CLOSED_PROJECTS_STATS_SUCCESS = 'DASHBOARD_CLOSED_PROJECTS_STATS_SUCCESS';
export const DASHBOARD_DAYS_TO_PLACEMENT_SUCCESS = 'DASHBOARD_DAYS_TO_PLACEMENT_SUCCESS';
export const DASHBOARD_PLACEMENT_DAYS_STATS_SUCCESS = 'DASHBOARD_PLACEMENT_DAYS_STATS_SUCCESS';
export const DASHBOARD_RECENT_REPORT_SUCCESS = 'DASHBOARD_RECENT_REPORT_SUCCESS';
export const DASHBOARD_ACTIVE_PROJECTS_STATS_SUCCESS = 'DASHBOARD_ACTIVE_PROJECTS_STATS_SUCCESS';
export const DASHBOARD_TASKS_SUCCESS = 'DASHBOARD_TASKS_SUCCESS';
export const DASHBOARD_DEALS_SUCCESS = 'DASHBOARD_DEALS_SUCCESS';
export const UPDATE_DASHBOARD_CARD_SEQUENCE = 'UPDATE_DASHBOARD_CARD_SEQUENCE';

// users
export const ACTIVE_USERS_LIST_SUCCESS = 'ACTIVE_USERS_LIST_SUCCESS';
export const USER_CHANGE_PER_PAGE = 'USER_CHANGE_PER_PAGE';
export const USER_CHANGE_PAGE_NUMBER = 'USER_CHANGE_PAGE_NUMBER';
export const USER_RELATED_PROJECTS_SUCCESS = 'USER_RELATED_PROJECTS_SUCCESS';
export const USER_RELATED_PROJECTS_FAILURE = 'USER_RELATED_PROJECTS_FAILURE';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAILURE = 'USER_UPDATE_FAILURE';
export const USERS_CHANGE_SORT_BY = 'USERS_CHANGE_SORT_BY';
export const REQUEST_USER_UPDATE = 'REQUEST_USER_UPDATE';
export const USER_LIST_FILTER = 'USER_LIST_FILTER';
export const USER_ACTIVE_PROJECTS_SUCCESS = 'USER_ACTIVE_PROJECTS_SUCCESS';
export const USER_ACTIVE_PROJECTS_FAILURE = 'USER_ACTIVE_PROJECTS_FAILURE';
export const USER_REINVITATION_SUCCESS = 'USER_REINVITATION_SUCCESS';
export const USER_REINVITATION_FAILURE = 'USER_REINVITATION_FAILURE';
export const USER_DEACTIVATE_SUCCESS = 'USER_DEACTIVATE_SUCCESS';
export const USER_DEACTIVATE_FAILURE = 'USER_DEACTIVATE_FAILURE';
export const USER_REACTIVATE_SUCCESS = 'USER_DEACTIVATE_SUCCESS';
export const USER_REACTIVATE_FAILURE = 'USER_DEACTIVATE_FAILURE';
export const REQUEST_USER_INFO_SUCCESS = 'REQUEST_USER_INFO_SUCCESS';
export const REQUEST_USER_INFO_FAILURE = 'REQUEST_USER_INFO_FAILURE';

// candidacies
export const REMOVE_CANDIDACY_SUCCESS = 'REMOVE_CANDIDACY_SUCCESS';
export const REMOVE_CANDIDACY_FAILURE = 'REMOVE_CANDIDACY_FAILURE';
export const CANDIDACY_NOTES_REQUEST = 'CANDIDACY_NOTES_REQUEST';
export const CANDIDACY_NOTES_SUCCESS = 'CANDIDACY_NOTES_SUCCESS';
export const CANDIDACY_NOTES_FAILURE = 'CANDIDACY_NOTES_FAILURE';
export const CANDIDACY_DETAIL_REQUEST = 'CANDIDACY_DETAIL_REQUEST';
export const CANDIDACY_DETAIL_FAILURE = 'CANDIDACY_DETAIL_FAILURE';
export const CANDIDACY_DETAIL_SUCCESS = 'CANDIDACY_DETAIL_SUCCESS';
export const ADD_NOTE_TO_CANDIDACY_SUCCESS = 'ADD_NOTE_TO_CANDIDACY_SUCCESS';
export const ADD_NOTE_TO_CANDIDACY_FAILURE = 'ADD_NOTE_TO_CANDIDACY_FAILURE';
export const UPDATE_CANDIDACIES_FIELDS_LIST = 'UPDATE_CANDIDACIES_FIELDS_LIST';
export const UPDATE_CANDIDACIES_COLUMN_WIDTHS = 'UPDATE_CANDIDACIES_COLUMN_WIDTHS';
export const UPDATE_CANDIDACY_NOTE_SUCCESS = 'UPDATE_CANDIDACY_NOTE_SUCCESS';
export const UPDATE_CANDIDACY_NOTE_FAILURE = 'UPDATE_CANDIDACY_NOTE_FAILURE';

// Notes
export const DELETE_NOTE_SUCCESS = 'DELETE_NOTE_SUCCESS';
export const DELETE_NOTE_FAILURE = 'DELETE_NOTE_FAILURE';
export const GET_FILEIN_OPTIONS_SUCCESS = 'GET_FILEIN_OPTIONS_SUCCESS';
export const GET_FILEIN_OPTIONS_FAILURE = 'GET_FILEIN_OPTIONS_FAILURE';

// Note Category
export const REQUEST_NOTE_CATEGORIES = 'REQUEST_NOTE_CATEGORIES';
export const NOTE_CATEGORIES_SUCCESS = 'NOTE_CATEGORIES_SUCCESS';
export const NOTE_CATEGORIES_ADD_SUCCESS = 'NOTE_CATEGORIES_ADD_SUCCESS';
export const NOTE_CATEGORIES_ADD_FAILURE = 'NOTE_CATEGORIES_ADD_FAILURE';
export const NOTE_CATEGORIES_UPDATE_FAILURE = 'NOTE_CATEGORIES_UPDATE_FAILURE';
export const NOTE_CATEGORIES_UPDATE_SUCCESS = 'NOTE_CATEGORIES_UPDATE_SUCCESS';
export const NOTE_CATEGORIES_DELETABLE_SUCCESS = 'NOTE_CATEGORIES_DELETABLE_SUCCESS';
export const NOTE_CATEGORY_DELETE_SUCCESS = 'NOTE_CATEGORY_DELETE_SUCCESS';
export const NOTE_CATEGORY_DELETE_FAILURE = 'NOTE_CATEGORY_DELETE_FAILURE';
export const REQUEST_REORDER_NOTE_CATEGORIES_LIST = 'REQUEST_REORDER_NOTE_CATEGORIES_LIST';
export const REORDER_NOTE_CATEGORY_SUCCESS = 'REORDER_NOTE_CATEGORY_SUCCESS';
export const REORDER_NOTE_CATEGORY_FAILURE = 'REORDER_NOTE_CATEGORY_FAILURE';

// Note Template
export const REQUEST_NOTE_TEMPLATES = 'REQUEST_NOTE_TEMPLATES';
export const NOTE_TEMPLATES_SUCCESS = 'NOTE_TEMPLATES_SUCCESS';
export const NOTE_TEMPLATE_ADD_SUCCESS = 'NOTE_TEMPLATE_ADD_SUCCESS';
export const NOTE_TEMPLATE_ADD_FAILURE = 'NOTE_TEMPLATE_ADD_FAILURE';
export const NOTE_TEMPLATE_UPDATE_SUCCESS = 'NOTE_TEMPLATE_UPDATE_SUCCESS';
export const NOTE_TEMPLATE_UPDATE_FAILURE = 'NOTE_TEMPLATE_UPDATE_FAILURE';
export const NOTE_TEMPLATE_DELETE_FAILURE = 'NOTE_TEMPLATE_DELETE_FAILURE';
export const NOTE_TEMPLATE_DELETE_SUCCESS = 'NOTE_TEMPLATE_DELETE_SUCCESS';
export const NOTE_TEMPLATE_CREATOR_SUCCESS = 'NOTE_TEMPLATE_CREATOR_SUCCESS';

// firms
export const FIRM_USER_LIST_SUCCESS = 'FIRM_USER_LIST_SUCCESS';
export const FIRM_USER_LIST_FAILURE = 'FIRM_USER_LIST_FAILURE';
export const FIRM_USER_LIST_REQUEST = 'FIRM_USER_LIST_REQUEST';
export const FIRM_DETAILS_SUCCESS = 'FIRM_DETAILS_SUCCESS';
export const FIRM_DETAILS_FAILURE = 'FIRM_DETAILS_FAILURE';
export const UPDATE_FIRM_INFO = 'UPDATE_FIRM_INFO';
export const UPDATE_FIRM_INFO_SUCCESS = 'UPDATE_FIRM_INFO_SUCCESS';
export const UPDATE_FIRM_INFO_FAILURE = 'UPDATE_FIRM_INFO_FAILURE';
export const FIRM_HIDE_FLASH_MESSAGE = 'FIRM_HIDE_FLASH_MESSAGE';
export const ADD_NEW_FIRM_USER = 'ADD_NEW_FIRM_USER';
export const ADD_NEW_FIRM_USER_SUCCESS = 'ADD_NEW_FIRM_USER_SUCCESS';
export const ADD_NEW_FIRM_USER_FAILURE = 'ADD_NEW_FIRM_USER_FAILURE';
export const FIRM_FEATURE_SUCCESS = 'FIRM_FEATURE_SUCCESS';
export const FIRM_FEATURE_FAILURE = 'FIRM_FEATURE_FAILURE';
export const UPDATE_FIRM_FEATURE_SUCCESS = 'UPDATE_FIRM_FEATURE_SUCCESS';
export const UPDATE_FIRM_FEATURE_FAILURE = 'UPDATE_FIRM_FEATURE_FAILURE';
export const FIRM_SETTINGS_SUCCESS = 'FIRM_SETTINGS_SUCCESS';
export const FIRM_SETTINGS_FAILURE = 'FIRM_SETTINGS_FAILURE';
export const UPDATE_FIRM_SETTINGS_SUCCESS = 'UPDATE_FIRM_SETTINGS_SUCCESS';
export const UPDATE_FIRM_SETTINGS_FAILURE = 'UPDATE_FIRM_SETTINGS_FAILURE';
export const MERGE_FIRM_TAGS_SUCCESS = 'MERGE_FIRM_TAGS_SUCCESS';
export const MERGE_FIRM_TAGS_FAILURE = 'MERGE_FIRM_TAGS_FAILURE';

// Firm Fields
export const FIRM_FIELDS_SUCCESS = 'FIRM_FIELDS_SUCCESS';
export const ADD_FIRM_FIELD_SUCCESS = 'ADD_FIRM_FIELD_SUCCESS';
export const ADD_FIRM_FIELD_FAILURE = 'ADD_FIRM_FIELD_FAILURE';
export const UPDATE_FIRM_FIELD_SUCCESS = 'UPDATE_FIRM_FIELD_SUCCESS';
export const UPDATE_FIRM_FIELD_FAILURE = 'UPDATE_FIRM_FIELD_FAILURE';
export const DELETE_FIRM_FIELD_SUCCESS = 'DELETE_FIRM_FIELD_SUCCESS';
export const DELETE_FIRM_FIELD_FAILURE = 'DELETE_FIRM_FIELD_FAILURE';

// recent visited entity
export const RECENT_VISITED_ENTITIES_LIST_SUCCESS = 'RECENT_VISITED_ENTITIES_LIST_SUCCESS';

// Overview Notes
export const UPDATE_CANDIDATE_OVERVIEW_FAILURE = 'UPDATE_CANDIDATE_OVERVIEW_FAILURE';
export const UPDATE_CANDIDATE_OVERVIEW_SUCCESS = 'UPDATE_CANDIDATE_OVERVIEW_SUCCESS';

// Investors
export const REQUEST_INVESTORS = 'REQUEST_INVESTORS';
export const INVESTOR_LIST_SUCCESS = 'INVESTOR_LIST_SUCCESS';
export const REQUEST_ADD_INVESTOR = 'REQUEST_ADD_INVESTOR';
export const ADD_INVESTOR_SUCCESS = 'ADD_INVESTOR_SUCCESS';
export const ADD_INVESTOR_FAILURE = 'ADD_INVESTOR_FAILURE';
export const UPDATE_INVESTOR_SUCCESS = 'UPDATE_INVESTOR_SUCCESS';
export const UPDATE_INVESTOR_FAILURE = 'UPDATE_INVESTOR_FAILURE';
export const INVESTOR_DELETABLE_SUCCESS = 'INVESTOR_DELETABLE_SUCCESS';
export const INVESTOR_DELETE_SUCCESS = 'INVESTOR_DELETE_SUCCESS';

// Industries
export const REQUEST_INDUSTRIES_LIST = 'REQUEST_INDUSTRIES_LIST';
export const INDUSTRIES_SUCCESS = 'INDUSTRIES_SUCCESS';
export const INDUSTRIES_ADD_SUCCESS = 'INDUSTRIES_ADD_SUCCESS';
export const INDUSTRIES_ADD_FAILURE = 'INDUSTRIES_ADD_FAILURE';
export const INDUSTRIES_UPDATE_SUCCESS = 'INDUSTRIES_UPDATE_SUCCESS';
export const INDUSTRIES_UPDATE_FAILURE = 'INDUSTRIES_UPDATE_FAILURE';
export const INDUSTRIES_DELETE_SUCCESS = 'INDUSTRIES_DELETE_SUCCESS';
export const INDUSTRIES_DELETE_FAILURE = 'INDUSTRIES_DELETE_FAILURE';
export const INDUSTRIES_DELETABLE_FAILURE = 'INDUSTRIES_DELETABLE_FAILURE';
export const INDUSTRIES_DELETABLE_SUCCESS = 'INDUSTRIES_DELETABLE_SUCCESS';
export const REQUEST_REORDER_INDUSTRIES_LIST = 'REQUEST_REORDER_INDUSTRIES_LIST';
export const REORDER_INDUSTRIES_SUCCESS = 'REORDER_INDUSTRIES_SUCCESS';
export const REORDER_INDUSTRIES_FAILURE = 'IREORDER_INDUSTRIES_FAILURE';

// Recruiters
export const USERS_ALL_ACTIVE_SUCCESS = 'USERS_ALL_ACTIVE_SUCCESS';
export const USERS_SELECTED_SUCCESS = 'USERS_SELECTED_SUCCESS';

// Firm statuses
export const FIRM_STATUSES_FAILURE = 'FIRM_STATUSES_FAILURE';
export const REQUEST_FIRM_STATUSES = 'REQUEST_FIRM_STATUSES';
export const STATUS_ADD_SUCCESS = 'STATUS_ADD_SUCCESS';
export const STATUS_ADD_FAILURE = 'STATUS_ADD_FAILURE';
export const STATUS_UPDATE_FAILURE = 'STATUS_UPDATE_FAILURE';
export const STATUS_UPDATE_SUCCESS = 'STATUS_UPDATE_SUCCESS';
export const STATUS_DELETE_SUCCESS = 'STATUS_DELETE_SUCCESS';
export const STATUS_DELETABLE_SUCCESS = 'STATUS_DELETABLE_SUCCESS';
export const STATUS_DELETE_FAILURE = 'STATUS_DELETE_FAILURE';
export const REQUEST_REORDER_FIRM_STATUSES_LIST = 'REQUEST_REORDER_FIRM_STATUSES_LIST';
export const REORDER_FIRM_STATUS_SUCCESS = 'REORDER_FIRM_STATUS_SUCCESS';
export const REORDER_FIRM_STATUS_FAILURE = 'REORDER_FIRM_STATUS_FAILURE';

export const CANDIDATES_MASS_MAIL_SUCCESS = 'CANDIDATES_MASS_MAIL_SUCCESS';

// Specialties
export const REQUEST_SPECIALTIES = 'REQUEST_SPECIALTIES';
export const SPECIALTIES_LIST_SUCCESS = 'SPECIALTIES_LIST_SUCCESS';
export const SPECIALTIES_LIST_FAILURE = 'SPECIALTIES_LIST_FAILURE';
export const ADD_SPECIALTY_SUCCESS = 'ADD_SPECIALTY_SUCCESS';
export const ADD_SPECIALTY_FAILURE = 'ADD_SPECIALTY_FAILURE';
export const UPDATE_SPECIALTY_SUCCESS = 'UPDATE_SPECIALTY_SUCCESS';
export const UPDATE_SPECIALTY_FAILURE = 'UPDATE_SPECIALTY_FAILURE';
export const SPECIALTY_DELETABLE_SUCCESS = 'SPECIALTY_DELETABLE_SUCCESS';
export const SPECIALTY_DELETE_SUCCESS = 'SPECIALTY_DELETE_SUCCESS';

// Seniorities
export const REQUEST_SENIORITIES = 'REQUEST_SENIORITIES';
export const SENIORITIES_LIST_SUCCESS = 'SENIORITIES_LIST_SUCCESS';
export const SENIORITIES_LIST_FAILURE = 'SENIORITIES_LIST_FAILURE';
export const ADD_SENIORITY_SUCCESS = 'ADD_SENIORITY_SUCCESS';
export const ADD_SENIORITY_FAILURE = 'ADD_SENIORITY_FAILURE';
export const UPDATE_SENIORITY_SUCCESS = 'UPDATE_SENIORITY_SUCCESS';
export const UPDATE_SENIORITY_FAILURE = 'UPDATE_SENIORITY_FAILURE';
export const SENIORITY_DELETABLE_SUCCESS = 'SENIORITY_DELETABLE_SUCCESS';
export const SENIORITY_DELETE_SUCCESS = 'SENIORITY_DELETE_SUCCESS';

// DealStatuses
export const REQUEST_DEAL_STATUSES = 'REQUEST_DEAL_STATUSES';
export const DEAL_STATUSES_LIST_SUCCESS = 'DEAL_STATUSES_LIST_SUCCESS';
export const DEAL_STATUSES_LIST_FAILURE = 'DEAL_STATUSES_LIST_FAILURE';
export const ADD_DEAL_STATUS_SUCCESS = 'ADD_DEAL_STATUS_SUCCESS';
export const ADD_DEAL_STATUS_FAILURE = 'ADD_DEAL_STATUS_FAILURE';
export const UPDATE_DEAL_STATUS_SUCCESS = 'UPDATE_DEAL_STATUS_SUCCESS';
export const UPDATE_DEAL_STATUS_FAILURE = 'UPDATE_DEAL_STATUS_FAILURE';
export const DEAL_STATUS_DELETABLE_SUCCESS = 'DEAL_STATUS_DELETABLE_SUCCESS';
export const DEAL_STATUS_DELETE_SUCCESS = 'DEAL_STATUS_DELETE_SUCCESS';
export const REQUEST_REORDER_DEAL_STATUSES_LIST = 'REQUEST_REORDER_DEAL_STATUSES_LIST';
export const REORDER_DEAL_STATUS_SUCCESS = 'REORDER_DEAL_STATUS_SUCCESS';
export const REORDER_DEAL_STATUS_FAILURE = 'REORDER_DEAL_STATUS_FAILURE';

// Screening Question
export const CREATE_SCREENING_QUESTION_SUCCESS = 'CREATE_SCREENING_QUESTION_SUCCESS';
export const CREATE_SCREENING_QUESTION_FAILURE = 'CREATE_SCREENING_QUESTION_FAILURE';
export const UPDATE_SCREENING_QUESTION_SUCCESS = 'UPDATE_SCREENING_QUESTION_SUCCESS';
export const UPDATE_SCREENING_QUESTION_FAILURE = 'UPDATE_SCREENING_QUESTION_FAILURE';
export const DELETE_SCREENING_QUESTION_SUCCESS = 'DELETE_SCREENING_QUESTION_SUCCESS';
export const DELETE_SCREENING_QUESTION_FAILURE = 'DELETE_SCREENING_QUESTION_FAILURE';
export const REQUEST_SCREENING_QUESTIONS = 'REQUEST_SCREENING_QUESTIONS';
export const SCREENING_QUESTIONS_LIST_SUCCESS = 'SCREENING_QUESTIONS_LIST_SUCCESS';
export const SCREENING_QUESTIONS_LIST_FAILURE = 'SCREENING_QUESTIONS_LIST_FAILURE';

// Candidacy Stats
export const REQUEST_SCREENING_QUESTIONS_RATINGS = 'REQUEST_SCREENING_QUESTIONS_RATINGS';
export const SCREENING_QUESTIONS_RATINGS_LIST_SUCCESS = 'SCREENING_QUESTIONS_RATINGS_LIST_SUCCESS';
export const SCREENING_QUESTIONS_RATINGS_LIST_FAILURE = 'SCREENING_QUESTIONS_RATINGS_LIST_FAILURE';
export const CREATE_SCREENING_QUESTIONS_RATINGS_SUCCESS = 'CREATE_SCREENING_QUESTIONS_RATINGS_SUCCESS';
export const CREATE_SCREENING_QUESTIONS_RATINGS_FAILURE = 'CREATE_SCREENING_QUESTIONS_RATINGS_FAILURE';

// Screening Report
export const CANDIDATE_SCREENING_REPORT = 'CANDIDATE_SCREENING_REPORT';

// Aggregate Notes
export const AGGREGATE_NOTES_REQUEST = 'AGGREGATE_NOTES_REQUEST';
export const AGGREGATE_NOTES_SUCCESS = 'AGGREGATE_NOTES_SUCCESS';
export const AGGREGATE_NOTES_FAILURE = 'AGGREGATE_NOTES_FAILURE';
export const UPDATE_AGGREGATE_NOTES_SUCCESS = 'UPDATE_AGGREGATE_NOTES_SUCCESS';
export const UPDATE_AGGREGATE_NOTES_FAILURE = 'UPDATE_AGGREGATE_NOTES_FAILURE';
export const ADD_AGGREGATE_NOTES_SUCCESS = 'ADD_AGGREGATE_NOTES_SUCCESS';
export const ADD_AGGREGATE_NOTES_FAILURE = 'ADD_AGGREGATE_NOTES_FAILURE';
export const DELETE_AGGREGATE_NOTE_SUCCESS = 'DELETE_AGGREGATE_NOTE_SUCCESS';
export const FETCH_PIN_NOTE_DATA_SUCCESS = 'FETCH_PIN_NOTE_DATA_SUCCESS';
export const CREATE_PIN_NOTE_SUCCESS = 'CREATE_PIN_NOTE_SUCCESS';
export const DESTROY_PIN_NOTE_SUCCESS = 'DESTROY_PIN_NOTE_SUCCESS';
export const UPDATE_AGGREGATE_NOTES_SHOW_REPLIES_LIST = 'UPDATE_AGGREGATE_NOTES_SHOW_REPLIES_LIST';
export const NOTE_CONTEXT_LIST_SUCCESS = 'NOTE_CONTEXT_LIST_SUCCESS';
export const REPLY_AGGREGATE_NOTE_SUCCESS = 'REPLY_AGGREGATE_NOTE_SUCCESS';
export const REPLY_AGGREGATE_NOTE_FAILURE = 'REPLY_AGGREGATE_NOTE_FAILURE';
export const FETCH_NOTE_SUCCESS = 'FETCH_NOTE_SUCCESS';
export const AGGREGATE_NOTES_NEEDS_REFRESH = 'AGGREGATE_NOTES_NEEDS_REFRESH';

// Candidacy List
export const STORE_LONG_LIST_SORTED_HEADER = 'STORE_LONG_LIST_SORTED_HEADER';
export const LONG_LIST_CHANGE_SORT_BY = 'LONG_LIST_CHANGE_SORT_BY';
export const UPDATE_LONG_LIST_COLUMN_WIDTHS = 'UPDATE_LONG_LIST_COLUMN_WIDTHS';
export const CANDIDACY_LIST_REQUEST = 'CANDIDACY_LIST_REQUEST';
export const CANDIDACY_LIST_FETCH_SUCCESS = 'CANDIDACY_LIST_FETCH_SUCCESS';
export const CANDIDACY_LIST_FETCH_FAILURE = 'CANDIDACY_LIST_FETCH_FAILURE';
export const CANDIDACY_LIST_CHANGE_PAGE_NUMBER = 'CANDIDACY_LIST_CHANGE_PAGE_NUMBER';
export const CANDIDACIES_VIEWS_SUCCESS = 'CANDIDACIES_VIEWS_SUCCESS';
export const CANDIDACIES_PERSON_REQUEST = 'CANDIDACIES_PERSON_REQUEST';
export const CANDIDACIES_PERSON_FETCH_SUCCESS = 'CANDIDACIES_PERSON_FETCH_SUCCESS';
export const CANDIDACIES_PERSON_FETCH_FAILURE = 'CANDIDACIES_PERSON_FETCH_FAILURE';
export const STATUS_REPORT_CANDIDACY_LIST_REQUEST = 'STATUS_REPORT_CANDIDACY_LIST_REQUEST';
export const STATUS_REPORT_CANDIDACY_LIST_SUCCESS = 'STATUS_REPORT_CANDIDACY_LIST_SUCCESS';
export const STATUS_REPORT_CANDIDACY_LIST_FAILURE = 'STATUS_REPORT_CANDIDACY_LIST_FAILURE';
export const CANDIDACY_RECENT_NOTE_SUCCESS = 'CANDIDACY_RECENT_NOTE_SUCCESS';

export const UPDATE_CANDIDACY_UNREAD_NOTIFICATION = 'UPDATE_CANDIDACY_UNREAD_NOTIFICATION';

// Project Types
export const REQUEST_PROJECT_TYPES = 'REQUEST_PROJECT_TYPES';
export const PROJECT_TYPES_LIST_SUCCESS = 'PROJECT_TYPES_LIST_SUCCESS';
export const PROJECT_TYPES_LIST_FAILURE = 'PROJECT_TYPES_LIST_FAILURE';
export const ADD_PROJECT_TYPE_SUCCESS = 'ADD_PROJECT_TYPE_SUCCESS';
export const ADD_PROJECT_TYPE_FAILURE = 'ADD_PROJECT_TYPE_FAILURE';
export const UPDATE_PROJECT_TYPE_SUCCESS = 'UPDATE_PROJECT_TYPE_SUCCESS';
export const UPDATE_PROJECT_TYPE_FAILURE = 'UPDATE_PROJECT_TYPE_FAILURE';
export const PROJECT_TYPE_DELETABLE_SUCCESS = 'PROJECT_TYPE_DELETABLE_SUCCESS';
export const PROJECT_TYPE_DELETE_SUCCESS = 'PROJECT_TYPE_DELETE_SUCCESS';
export const PROJECT_TYPE_SUCCESS = 'PROJECT_TYPE_SUCCESS';
export const PROJECT_TYPE_FAILURE = 'PROJECT_TYPE_FAILURE';
export const UPDATE_PROJECT_TYPE_STATUSES_SUCCESS = 'UPDATE_PROJECT_TYPE_STATUSES_SUCCESS';
export const UPDATE_PROJECT_TYPE_STATUSES_FAILURE = 'UPDATE_PROJECT_TYPE_STATUSES_FAILURE';
export const PROJECT_TYPE_STATUSES_SUCCESS = 'PROJECT_TYPE_STATUSES_SUCCESS';

// Email List
export const CREATE_EMAIL_LIST_SUCCESS = 'CREATE_EMAIL_LIST_SUCCESS';
export const CREATE_EMAIL_LIST_FAILURE = 'CREATE_EMAIL_LIST_FAILURE';

// Project Dashboard
export const PROJECT_ANALYTICS_SUMMARY_SUCCESS = 'PROJECT_ANALYTICS_SUMMARY_SUCCESS';
export const PROJECT_ANALYTICS_SUMMARY_FAILURE = 'PROJECT_ANALYTICS_SUMMARY_FAILURE';
export const PROJECT_ANALYTICS_OUTREACH_SUCCESS = 'PROJECT_ANALYTICS_OUTREACH_SUCCESS';
export const PROJECT_ANALYTICS_OUTREACH_FAILURE = 'PROJECT_ANALYTICS_OUTREACH_FAILURE';
export const PROJECT_ANALYTICS_CANDIDATES_ADDED_SUCCESS = 'PROJECT_ANALYTICS_CANDIDATES_ADDED_SUCCESS';
export const PROJECT_ANALYTICS_CANDIDATES_ADDED_FAILURE = 'PROJECT_ANALYTICS_CANDIDATES_ADDED_FAILURE';
export const UPDATE_PROJECT_NOTES_SHOW_REPLIES_LIST = 'UPDATE_PROJECT_NOTES_SHOW_REPLIES_LIST';
export const REQUEST_PROJECT_ANALYTICS_CUSTOM_FIELD_STATS_SUCCESS = 'REQUEST_PROJECT_ANALYTICS_CUSTOM_FIELD_STATS_SUCCESS';
export const REQUEST_PROJECT_ANALYTICS_CUSTOM_FIELD_STATS_FAILURE = 'REQUEST_PROJECT_ANALYTICS_CUSTOM_FIELD_STATS_FAILURE';

// Person Custom Fields
export const UPDATE_PERSON_CUSTOM_FIELDS_SUCCESS = 'UPDATE_OR_DELETE_PERSON_CUSTOM_FIELDS_SUCCESS';
export const UPDATE_PERSON_CUSTOM_FIELDS_FAILURE = 'UPDATE_OR_DELETE_PERSON_CUSTOM_FIELDS_FAILURE';
export const PERSON_CUSTOM_FIELDS_SUCCESS = 'PERSON_CUSTOM_FIELDS_SUCCESS';
export const PERSON_CUSTOM_FIELDS_FAILURE = 'PERSON_CUSTOM_FIELDS_FAILURE';

// CUSTOM REPORTS
export const FETCH_CUSTOM_REPORTS_SUCCESS = 'FETCH_CUSTOM_REPORTS_SUCCESS';
export const REQUEST_CUSTOM_REPORT_DOWNLOAD_LINK_SUCCESS = 'REQUEST_CUSTOM_REPORT_DOWNLOAD_LINK_SUCCESS';

// Company
export const COMPANY_AUTOCOMPLETE_SUCCESS = 'COMPANY_AUTOCOMPLETE_SUCCESS';
