export const FETCH_API_KEYS_SUCCESS = 'FETCH_API_KEYS_SUCCESS';
export const API_KEYS_REQUEST = 'API_KEYS_REQUEST';
export const API_KEYS_SET_CREDENTIALS = 'API_KEYS_SET_CREDENTIALS';
export const API_KEYS_SET_MESSAGE = 'API_KEYS_SET_MESSAGE';
export const API_KEYS_HIDE_FLASH_MESSAGE = 'API_KEYS_HIDE_FLASH_MESSAGE';
